services:
  - type: web
    name: healthcare-chatbot-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python -m gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: backend

  - type: web
    name: healthcare-chatbot-frontend
    env: static
    buildCommand: cd healthcare-chatbot-frontend && npm install && npm run build
    staticPublishPath: healthcare-chatbot-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 